sudo: required
language: node_js
node_js:
  - "8.5"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

dist: trusty

addons:
  chrome: stable

script:
  - "./ci/script.sh"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start